### ISSUE TITLE
Cant be added 

### ISSUE THREAD

**Issue by bajro17** [ZingyTomato/Niko-Music#1]
![Screenshot](https://user-images.githubusercontent.com/16452914/147821515-fffb32d3-23c7-4356-83bf-19e294365d2f.png)

**Comment by ZingyTomato** [comment]
Yes the bot can't be added right now as Discord has marked its growth as "Suspicious". I have sent them a support request so hopefully this can be over soon.

**Comment by bajro17** [comment]
I finally added it but now I cant use it whatever command I try niko @niko @Niko Music nothing work can you please tell me what is command for using it

**Comment by ZingyTomato** [comment]
Yeah so in order to verify the bot, I can't apply for the message intent (because discord wants to push slash commands), In order to get around this, I've had to change the prefix from niko to just pinging the bot. You need to type @Niko Music (Mention the bot not the role) help. Hope this helps
